apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zookeeper
  name: zookeeper
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec: 
      containers:
      - name: zookeeper
        image: zookeeper
        imagePullPolicy: "Always"
        resource:
        ports:
          - containerPort: 2181

