
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka
        imagePullPolicy: "Always"
        env:
          - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
            value: "THIS_STRING_IS_REPLACED_DURING_BUILD"                   
        envFrom:
          - configMapRef:
              name: configmap-kafka
        resource:
        ports:
        - containerPort: 9092